CC = g++
FLAGS = -Wshadow -Winit-self -Wredundant-decls -Wcast-align -Wundef -Wfloat-equal -Winline -Wunreachable-code -Wmissing-declarations -Wmissing-include-dirs -Wswitch-enum -Wswitch-default -Weffc++ -Wmain -Wextra -Wall -g -pipe -fexceptions -Wcast-qual -Wconversion -Wctor-dtor-privacy -Wempty-body -Wformat-security -Wformat=2 -Wignored-qualifiers -Wlogical-op -Wno-missing-field-initializers -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Wsign-promo -Wstack-usage=8192 -Wstrict-aliasing -Wstrict-null-sentinel -Wtype-limits -Wwrite-strings -Werror=vla -D_DEBUG -D_EJUDGE_CLIENT_SIDE
IFLAGS = -Iinclude
OBJECTS = main.o strings.o my_assert.o file_processing.o cmd_input.o myqsort.o comparators.o bubblesort.o

all: $(OBJECTS)
	$(CC) $(OBJECTS) -o StringsSorting	

main.o: main.cpp
	$(CC) $(FLAGS) $(IFLAGS) -c $^  -o $@

strings.o: strings.cpp
	$(CC) $(FLAGS) $(IFLAGS) -c $^  -o $@

my_assert.o: my_assert.cpp
	$(CC) $(FLAGS) $(IFLAGS) -c $^  -o $@

file_processing.o: file_processing.cpp
	$(CC) $(FLAGS) $(IFLAGS) -c $^  -o $@

cmd_input.o: cmd_input.cpp
	$(CC) $(FLAGS) $(IFLAGS) -c $^  -o $@

myqsort.o: myqsort.cpp
	$(CC) $(FLAGS) $(IFLAGS) -c $^  -o $@

comparators.o: comparators.cpp
	$(CC) $(FLAGS) $(IFLAGS) -c $^  -o $@

bubblesort.o: bubblesort.cpp
	$(CC) $(FLAGS) $(IFLAGS) -c $^  -o $@

clean:
	rm -f *.o *~ core *~ *.exe